version: '3'

services:
  nginx:
    image: containers_repos_domain/devops/nginx:nginx_tag
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ~/log/nginx:/var/log/nginx
      - nodejs-static:/var/static/nodejs
      - django-static:/var/static/django
    links:
      - nodejs
      - django
    restart: always
  nodejs:
    image: containers_repos_domain/devops/nodejs:nodejs_tag
    container_name: nodejs
    volumes:
      - ~/log/nodejs:/home/node/pm2logs
      - nodejs-static:/usr/src/app/public
    environment:
        NODE_ENV: production
    restart: always
  django:
    image: containers_repos_domain/devops/django:django_tag
    container_name: django
    volumes:
      - ~/log/django:/var/log
      - django-static:/var/django
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_prod
    restart: always

volumes:
  nodejs-static:
  django-static:
