version: '3'

services:
  nginx:
    build: ./nginx
    image: devops/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ~/log/nginx:/var/log/nginx
      - nodejs-static:/var/static/nodejs
    links:
      - nodejs
  nodejs:
    build: ./nodejs
    image: devops/nodejs
    container_name: nodejs
    volumes:
      - ~/log/nodejs:/home/node/pm2logs
      - nodejs-static:/usr/src/app/public
    environment:
        NODE_ENV: production
  django:
    build: ./django
    image: devops/django
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ~/log/django:/var/log
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_prod

volumes:
  nodejs-static:
